server:
  port: 8080

spring:
  application:
    name: looky

  # 업로드 제한
  servlet:
    multipart:
      max-file-size: 50MB    # 개별 파일 용량
      max-request-size: 50MB # 요청 전체 용량

  #  문서화 (Swagger)
  springdoc:
    swagger-ui:
      path: /docs
    api-docs:
      path: /v3/api-docs
    show-actuator: true
    default-consumes-media-type: application/json
    default-produces-media-type: application/json

  # 클라우드 설정
  cloud:
    aws:
      s3:
        bucket: ${BUCKET_NAME}
      region: ap-northeast-2
      credentials:
        access-key: ${IAM_ACCESS_KEY}
        secret-key: ${IAM_SECRET_KEY}

  # 메일 설정
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SPRING_MAIL_USERNAME}
    password: ${SPRING_MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

app:
  email:
    from: ${SPRING_MAIL_USERNAME}
    verification:
      ttl-minutes: 5
  redirect-uris: # 소셜 로그인 리다이렉트 URI
    web: "http://localhost:5173/oauth/callback" # 웹에서 요청 시
    app: "rnapp://auth/callback"                # 앱에서 요청 시
    
# JWT 정책
jwt:
  secret: ${JWT_SECRET}
  access-expiration: 3600000
  refresh-expiration: 1209600000

# open api 설정
open-api:
  service-key: ${OPEN_API_KEY}

# Naver Maps API
naver:
  maps:
    client-id: ${NAVER_MAP_CLIENT_ID}
    client-secret: ${NAVER_MAP_CLIENT_SECRET}

